### ISSUE TITLE
Memory problem?

### ISSUE THREAD

**Issue by ujovlado** [keboola/processor-skip-lines#12]
https://keboola.zendesk.com/agent/tickets/8194

Setting memory from default to 512m solved this - but maybe temporarily.

**Comment by odinuv** [comment]
tak to nevim, zkusil jsem to i na gigovym souboru a vpohode se to vejde do 14mb pameti i swap

**Comment by odinuv** [comment]
jeste teda doplnim chybovou hlasku
```
Symfony\Component\Process\Exception\ProcessFailedException:The command "tail -n +2 '/data/in/tables/threads/tt_threads.csv.gz.csv-tt_threads.csv' > '/data/out/tables/threads/tt_threads.csv.gz.csv-tt_threads.csv'" failed.

Exit Code: 1(General error)

Working directory: /code

Output:
================


Error Output:
================
tail: error writing 'standard output': Cannot allocate memory

File: /code/vendor/symfony/process/Process.php
Line: 239
Code: 0
Trace: #0 /code/src/processFile.php(34): Symfony\Component\Process\Process->mustRun()
#1 /code/main.php(42): Keboola\Processor\SkipLines\processFile(Object(Symfony\Component\Finder\SplFileInfo), '/data/out/table...', Array)
#2 {main}
```

**Comment by odinuv** [comment]
closing in favor of https://github.com/keboola/docker-bundle/issues/267
